export const MOCK_CURRENT_DATE = new Date(2025, 3, 4, 18, 0, 0);
export const MOCK_CURRENT_TIMESTAMP_MS = MOCK_CURRENT_DATE.getTime();
export const MOCK_CURRENT_TIMESTAMP_SEC = MOCK_CURRENT_TIMESTAMP_MS / 1000;
